import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { BottomSheetProvider } from "@/Providers/BottomSheetProvider";

const vazir = Vazirmatn({
  subsets: ["arabic"], // Includes Persian glyphs
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        dir="rtl"
        className={`${vazir.className} antialiased mx-auto max-w-[512px] min-h-screen`}
      >
        <BottomSheetProvider>
          {children}
          <div id="bottom-sheet-root" />
        </BottomSheetProvider>
      </body>
    </html>
  );
}
